services:
  5etools-docker:
    container_name: 5etools-docker
    image: ghcr.io/mstewart14/5etools-docker
    volumes:
      - ~/5etools-docker/htdocs:/usr/local/apache2/htdocs
    ports:
     - 8080:80/tcp
    environment:
     - DL_LINK=https://github.com/5etools-mirror-3/5etools-src.git
     - IMG_LINK=https://github.com/5etools-mirror-3/5etools-img.git
     - IMG=FALSE # Set to TRUE to pull images from https://github.com/5etools-mirror-2/5etools-img (as a Git submodule)
     #- OFFLINE_MODE=TRUE # Optional. Expects "TRUE" or "FALSE". Disables checking for new updates.

# Uncomment this block to use a docker-managed volume:
#volumes:
#  5etools-docker:
