name: CI/CD

on:
  # Triggers the workflow when changes are made to the image on the main branch
  push:
    branches: [ main ]
    paths-ignore: # don't run this workflow if no changes have been made to the docker image
      - '.github/**'
      - 'docker-compose.yml'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore: # don't run this workflow if no changes have been made to the docker image
      - '.github/**'
      - 'docker-compose.yml'
      - 'README.md'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  ci:
    name: Build and push Docker image to ghcr
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      artifact-metadata: write
      deployments: write      
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.MY_USER }}
          password: ${{ secrets.MY_TOKEN }}     
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mstewart14/5etools-docker
          tags: mstewart14/5etools-docker:latest
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      
      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
